# mcp_openapi/driver_base.py
from __future__ import annotations
from typing import Any, Dict, List, Optional, Protocol

class CacheAPI(Protocol):
    def get(self, ns: str, key: str) -> Optional[Any]: ...
    def set(self, ns: str, key: str, value: Any, ttl_seconds: Optional[int] = None) -> None: ...
    def delete(self, ns: str, key: str) -> None: ...
    def namespace(self) -> str: ...

class Driver(Protocol):
    name: str
    async def load(self, config: Dict[str, Any], cache: CacheAPI) -> None: ...
    async def describe(self) -> Dict[str, Any]: ...
    async def enrich_openapi(self, openapi_schema: Dict[str, Any]) -> None: ...
    async def close(self) -> None: ...

    # optional helpers (if present, app.py will use them)
    def openapi_tags(self) -> List[Dict[str, Any]]: ...
    def tool_guidance(self, tool_name: str, td: Any) -> Dict[str, Any]: ...
    def extend_model_instructions(self, inst: Dict[str, Any]) -> None: ...
    def summarize_cache(self) -> Dict[str, Any]: ...
